version: '3.1'

networks: 
    tech_challenge_net:
      driver: bridge

services:

  mongo:
    image: mongo:latest
    restart: always
    networks:
      - tech_challenge_net
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root!
    ports:
      - "27017:27017"
      
  web:
    image: techchallenge-api:v1
    depends_on:
      - mongo
    networks:
      - tech_challenge_net
    ports:
      - "8080:8080"